
name: continuous delivery

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

env:
  type: "none"
  file: "none"
  location: "none"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

        - name: setup
          uses: chrisdickinson/setup-yq@latest

        - name: Checkout Out Expected State
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Retrieve Deployment Configuration
          id: set_var
          run: |
            echo "type=$(yq r githubpages.yaml '.deploy.type')" >> $GITHUB_ENV
            echo "file=$(yq r githubpages.yaml '.deploy.file')" >> $GITHUB_ENV
            echo "location=$(yq r githubpages.yaml '.deploy.location')" >> $GITHUB_ENV

        - name: Echo Out Deployment Configuration Variables
          run: |
            echo "${{env.type}}"
            echo "${{env.location}}"
            echo "${{env.file}}"

        # - name: Download Artifacts
        #   uses: actions/download-artifact@v2

        # - name: UnZip Artifacts
        #   uses: actions/download-artifact@v2

        # - name: Deploy to GitHub Pages
        #   id: deployment
        #   uses: actions/deploy-pages@v2 