
name: continuous delivery

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

env:
  type: "none"
  tag: "none"
  repository: "none"

jobs:
    build:

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
          pages: write      # to deploy to Pages
          id-token: write   # to verify the deployment originates from an appropriate source

        runs-on: ubuntu-latest

        steps:

        - name: setup
          run: |
            yq --help
            yq --version

        - name: Checkout Out Expected State
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Retrieve Deployment Configuration
          id: set_var
          run: |
            echo "type=$(yq '.deploy.type' < githubpages.yaml)" >> $GITHUB_ENV
            echo "tag=$(yq '.deploy.tag' < githubpages.yaml)" >> $GITHUB_ENV
            echo "repository=$(yq '.deploy.repository' < githubpages.yaml)" >> $GITHUB_ENV

        - name: Echo Out Deployment Configuration Variables
          run: |
            echo "${{env.type}}"
            echo "${{env.tag}}"
            echo "${{env.repository}}"

        - name: Download Artifact
          id: downloadstep
          uses: robinraju/release-downloader@v1.8
          with:
            repository: "${{env.repository}}"
            tag: "${{env.tag}}"
            extract: true

        - name: Echo Out Download Artifact Variables
          run: |
            echo "${{ fromJson(steps.downloadstep.outputs.downloaded_files)[0] }}"

        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v3

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2 
          with:
            artifact_name:  ${{ fromJson(steps.downloadstep.outputs.downloaded_files)[0] }}