
name: continuous delivery

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

env:
  type: "none"
  tag: "none"
  repository: "none"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

        - name: setup
          run: |
            yq --help
            yq --version

        - name: Checkout Out Expected State
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Retrieve Deployment Configuration
          id: set_var
          run: |
            echo "type=$(yq '.deploy.type' < githubpages.yaml)" >> $GITHUB_ENV
            echo "tag=$(yq '.deploy.file' < githubpages.yaml)" >> $GITHUB_ENV
            echo "repository=$(yq '.deploy.location' < githubpages.yaml)" >> $GITHUB_ENV

        - name: Echo Out Deployment Configuration Variables
          run: |
            echo "${{env.type}}"
            echo "${{env.tag}}"
            echo "${{env.repository}}"

        - name: Download Artifact
          uses: robinraju/release-downloader@v1.8
          with:
            repository: "owner/repo"
            tag: "${{env.tag}}"
            fileName: "demo-cicd-webapp.zip"
            extract: true

        # - name: Deploy to GitHub Pages
        #   id: deployment
        #   uses: actions/deploy-pages@v2 